### ISSUE TITLE
FlavorRef type is ambiguous

### ISSUE THREAD

**Issue by jamiehannaford** [rackerlabs/docs-cloud-databases#4]
For `4.2.1 Create database instance` operation, the following definition is given for flavorRef:

> Reference (href) to a flavor as specified in the response from the List Flavors API call. **This is the actual URI as specified by the href field in the link.** Refer to the List Flavors response examples that follow for an example of the flavorRef.

But the JSON sample provides an integer ID as the flavorRef (`1`). Which type is correct?

**Comment by masthalter** [comment]
Hi Jamie,

Please see the following Note for the attribute flavorRef in Table 4.1 "Required and optional attributes for Create  instance" in section 4.2.1 "Create database instance":

Note
Rather than the flavor URI, you can also
pass the flavor id (integer) as the value for
flavorRef.

So the answer is, "you can provide either the flavor URI, or the flavor id (integer)".

Regards,

Mike
________________________________

**Comment by jamiehannaford** [comment]
@masthalter Ah okay :+1: Mondays...
